# Generated by Django 6.0.5 on 2026-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_message_post_comment_friendship_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tag', models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('top', 'Top')], default='new', max_length=20)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
